[bazel][libc][NFC] Add missing layering deps (#107947)
After 01f78a17b49f5db630598dbc22dfe9431109dbb8

e.g.

```
external/llvm-project/libc/test/src/math/smoke/NextTowardTest.h:12:10: error: module llvm-project//libc/test/src/math/smoke:nexttowardf_test does not depend on a module exporting 'src/__support/CPP/bit.h'
```