Revert "[llvm] add zstd to llvm::compression namespace"
This reverts commit 164a868b55df152e9ad5e88b441711f40e47acea.

Breaks macOS builds with this:
llvm/lib/Support/Compression.cpp:24:10: fatal error: 'zstd.h' file not found