[libcxx] Bump __libcpp_version to 14 after branch
This was missed in 53c23a687cc89b733726573e17f1fd36716a0959
and caused test failures in the buildkite bots:
libcpp_version.pass.cpp:22:1:
error: static_assert failed due to requirement '14000 == libcpp_version'
"_LIBCPP_VERSION doesn't match __libcpp_version