[bazel] Turn off layering_check for //llvm/unittests:target_aarch64_tests
llvm/unittests/Target/AArch64/AArch64SVESchedPseudoTest.cpp:38:10: error: module @llvm-project//llvm/unittests:target_aarch64_tests does not depend on a module exporting 'AArch64GenInstrInfo.inc'

Test was added in eb8c7f55eadb77cd93305f5d9598f88e81c33906